permalink: /:title.html
url: "http://playAnalyzer.com"
full_name: "Kevin M. Karol"
first_name: "Kevin"
last_name: "Karol"
blog_title: "Play Analyzer"
disqus_shortname: "kevinmkarol"
copyright_year: "2016"
google_analytics_code: "UA-64791632-3"
twitter: "kevinmkarol"
github: "kevinmkarol"
port: 1865
goodreads: "user/show/53476707-kevin-karol"
linkined_url: "https://www.linkedin.com/in/kevin-karol-292b0b53"
